### ISSUE TITLE
I missed you so much

### ISSUE THREAD

**Issue by rakisaionji** [samyuu/EvenMoreLegitArcadeController#16]
Hi @Samyuu. How do you do now?

It has been a long time I did not heard any about you. Are you still okay? Is there anything wrong? What are you working on now?

I'm very worried about you to the extend that I cannot even sleep. I hope you are still alive and doing well.

Love you,
Raki.

**Comment by blueskythlikesclouds** [comment]
I don't think GitHub is the place to ask this.

**Comment by Filo97** [comment]
Good fucking god Raki ever considered people just don't wanna talk to you? Also this is definitely not an issue with ELAC.

**Comment by cainan-c** [comment]
i didnt fuck my cat. i didnt cum on my cat. i didnt put my dick anywhere near my cat. Ive never done anything weird with my cats. I promised myself i wasnt going to make apology videos after last years thing so im just trying to be as short and honest with this as possible. (1/?)

**Comment by rakisaionji** [comment]
I don't think GitHub is a place for kiddo who can't even code like @Filo97.

**Comment by Filo97** [comment]
@rakisaionji I can compile however, and as GitHub is a place where people share source codes i can compile the ones present in the vast library of GitHub whenever i want to try out latest features, a code just straight up doesn't have a release or i want to report a bug.

**Comment by rakisaionji** [comment]
Don't show your stupidity here kiddo. There are bunch of professionals here. Coding is programming and I doubt that you are talent enough to do something big like @Samyuu.

**Comment by Filo97** [comment]
That is perfectly true and i never said i was (at least not yet, who knows, maybe one day?). I just said, GitHub is also a platform where users can compile source code to try out latest commits and report bugs. I can't code, sure, but i CAN try out things and report bugs if i notice them. Without being an asshole to everyone around me too.

**Comment by rakisaionji** [comment]
Okay. So please report the bugs in your Project Diva Arcade Future Tone Version B Revision 3 (7.10.00) to SEGA. I believe that those bugs are still not being fixed in the last update.

**Comment by Filo97** [comment]
Honey no. I mean that if i notice a bug in ELAC itself i can report them to samyuu, but it doesn't have to be ELAC. It can be any GitHub program. Your "Filo can't be on GitHub 'cause he can't code" logic makes no sense. I can't code, but i can report bugs to people if i notice them. Or i can simply compile latest source code when i want a newer version than latest release.

**Comment by rakisaionji** [comment]
Holy hell. Your action with ELAC did not help any development progress. Just fork it and change its strings to your degenerate shits really not help. Are you a retard or what?

**Comment by Filo97** [comment]
Can you tell when things are made for jokes holy shit? I was really bored and had nothing better to do. Do you have to dictate what i do with my free time when i'm really bored? Am i not allowed to wear pink if you don't want me to 'cause our great lord Raki said so?

**Comment by Filo97** [comment]
Anyway, i'm done arguing with you. You're honestly really tiring Raki.
