### ISSUE TITLE
PV viewing and character switching in-game?

### ISSUE THREAD

**Issue by MarieRose1301** [samyuu/EvenMoreLegitArcadeController#18]
Was wondering why is it impossible to change the charas(triangle grayed out) or watch the video alone in the game? Is there a reason for having the characters set as ids in ini file?

**Comment by cainan-c** [comment]
For viewing PVs, Press Triangle on this screen:
![image](https://user-images.githubusercontent.com/30056568/54958493-b472a880-4f4d-11e9-99ec-ba84eede8980.png)
Press the PV Button and press circle twice:
![image](https://user-images.githubusercontent.com/30056568/54958501-be94a700-4f4d-11e9-8cc7-5f8dbbef6f2f.png)
Select the PV and enjoy!
![image](https://user-images.githubusercontent.com/30056568/54958527-edab1880-4f4d-11e9-93d3-2b5ec4fa5a5b.png)
![image](https://user-images.githubusercontent.com/30056568/54958593-3367e100-4f4e-11e9-9951-5858fe6000e5.png)
