### ISSUE TITLE
cant open pv mode and no mouse cursor

### ISSUE THREAD

**Issue by SiLPHER401** [samyuu/EvenMoreLegitArcadeController#19]
1.the button of the pv mode is grey colour and nothing happen after pressing it (picture show below). Please tell me how to fix it (a project diva game with no pv is not a project diva game).
![Screenshot (290)](https://user-images.githubusercontent.com/45973280/55011541-fae50780-5020-11e9-9acd-9506ea033da2.png)

2.my mouse cursor is invisible every time i open the diva.exe , its still function but you cant see the cursor. It can be visible by pressing f3 twice to able and disable the camera controller (the camera controller will hide the cursor while using it and cancel hiding it , so i use this to bring my cursor back). But i still wish that this error can be fix.

**Comment by samyuu** [comment]
Both of these additions are part of the [patch.txt](https://github.com/samyuu/EvenMoreLegitArcadeController/blob/2020dee995e10de7532c955970902aac4e3fd99d/Prepatch/rom/patch.txt#L78) patch file of which the newer version does not appear to have been applied to your diva executable. 
Please try prepatch-ing an unedited `diva.exe` using the *newer* v4.0 `patch.txt`, making sure it does not throw any errors and test whether the problem persists.

The executable needs to be repatched with every update to ensure correct operation of ELAC.

**Comment by SiLPHER401** [comment]
yup it works now , turns out that my patching got some error
