### ISSUE TITLE
I Found out how to change the costume

### ISSUE THREAD

**Issue by MoePus** [samyuu/EvenMoreLegitArcadeController#2]
Thiscall(0x6D9C00,0x1027DA0, 0)+404  saves the costume id of character A.
Thiscall(0x6D9C00,0x1027DA0, 0)+408  saves the costume id of character B.

And if you hook 0x72B2C0 (which is generally called from 0x73DE37) you can change hair and cloth separately.
in the function 0x1F4 means default hair id and 0x1 means default cloth.

Would you add this to Elac?

**Comment by samyuu** [comment]
This is interesting though how would you suggest this be dynamically controlled by the user?
If my memory serves me right getting the module selection screen to work fully requires making significant modifications because the available module list is requested based on the user's DIVA.NET account.

**Comment by rakisaionji** [comment]
I think I can make a GUI for that. But it would take a couple week to have it working good. And this method is not so practical tho.
However, emulating that networking crap is the best approach, need someone help me to reverse engineering to find the endpoints inside the exe and I can try to simulate the requests.

**Comment by MoePus** [comment]
Maybe just by key pageup and pagedown?
I think players will just be happy if they can control this any way

**Comment by Yukikami39** [comment]
Better way would be to make a GUI with scrolling text button to switch singer and their costume/hair separately
like for example: 
Singer: Miku
Costume: Default
Hair: Default
(though for hairs it won't work properly, since their headsets and such are on their bodies, unlike in FT being included in the hair. And some accessories are loaded separately)

**Comment by blueskythlikesclouds** [comment]
Perhaps we could at least make it change the modules to the recommended ones?

**Comment by Yukikami39** [comment]
FT has option like that yeah, in the PV_DB as pv_costume=## , but PDA doesn't have it, and that command does not work.
